#!/usr/bin/env -S just --justfile

set fallback := true
set unstable := true

package := "obsidian"

_:
    @just --list

[env("NIXPKGS_ALLOW_UNFREE", "1")]
build:
    nix build --impure ".#{{ package }}"
