---
name: CI
on:
  pull_request:
  push:
    branches:
      - main
permissions:
  contents: read
jobs:
  flake-check:
    name: Flake Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: DeterminateSystems/determinate-nix-action@main
        with:
          extra-conf: |
            experimental-features = nix-command flakes
      - name: Run flake check
        env:
          NIXPKGS_ALLOW_UNFREE: "1"
        run: nix flake check --impure --no-write-lock-file
